version: "3"
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: semperflies
    ports:
      - "6500:5432"
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - ./.env
  pgAdmin:
    image: dpage/pgadmin4
    container_name: semperfliesAdmin
    ports:
      - "5050:80"
    env_file:
      - ./.env
volumes:
  progresDB:
