[model]
provider="Anthropic"
api_key="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"
# api_key="sk-proj-HAJWA4oLzVyNtJDaGvFRT3BlbkFJe8kLaR7zkjbWj1xEAW8Z"

[database]
namespace="semperflies" 
database="semperflies"
user="root"
pass="root"


